policies:
    - type: commit
      spec:
          gpg: false
          spellchecker:
              locale: US
          conventional:
              types:
                  - "type"
              scopes:
                  - "scope"
              descriptionLength: 72
    - type: license
      skipPaths:
          - .git
          - .build*/
      includeSuffixes:
          - .ext
      excludeSuffixes:
          - exclude-ext-prefix.ext
      header: |
          This is a license header.
