version: "3.8"

services:
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
        privileged: true
    web:
        build:
            context: .
            args:
                app_username: ${PROJECT_NAME}
                app_groupname: ${PROJECT_NAME}
        env_file: .env

        environment:
            # Override MONGO_HOST with the container IP
            # on the network Docker creates.
            MONGO_HOST: mongo
        command: |
            uvicorn adagiovanni.main:app
                --workers 1
                --host 0.0.0.0
                --port 8000
                --factory
        volumes:
            - appdata:/home/${PROJECT_NAME}/app/data/
        ports:
            - 8000:8000
        depends_on:
            - mongo
volumes:
    db:
    appdata:
